language: python
python: "2.7.13"

branches:
  - master
  - devel

os:
  - linux

#env variables
env:
  global:
  - RADICAL_PILOT_DBURL="mongodb://entk:entk123@127.0.0.1:27017/entk_test"
  - CODECOV_TOKEN="790b223f-07e4-4707-bb97-3abe58e29cd8"

# command to install dependencies
install:
  - pip install .
  - pip install coverage
  - pip install codecov

before_script:
  - sleep 20  # Ensures mongodb service is up
  - mongo entk_test --eval 'db.createUser({user:"entk",pwd:"entk123",roles:["readWrite"]});'

script:
  - LOC=`which python`
  - sed -i 's|VENV|'"$LOC"'|g' .coveragerc
  - coverage run -m pytest -vvv tests/test_component/test_amgr.py
  - coverage run -m pytest -vvv tests/test_component/test_modules.py
  - coverage run -m pytest -vvv tests/test_component/test_pipeline.py
  - travis_wait coverage run -m pytest -vvv tests/test_component/test_rmgr_2.py
  - travis_wait coverage run -m pytest -vvv tests/test_component/test_rmgr.py
  - coverage run -m pytest -vvv tests/test_component/test_stage.py
  - coverage run -m pytest -vvv tests/test_component/test_task.py
  - coverage run -m pytest -vvv tests/test_component/test_tmgr_2.py
  - coverage run -m pytest -vvv tests/test_component/test_tmgr_rp_utils_2.py
  - coverage run -m pytest -vvv tests/test_component/test_tmgr_rp_utils.py
  - coverage run -m pytest -vvv tests/test_component/test_tmgr.py
  - coverage run -m pytest -vvv tests/test_component/test_wfp.py
  - coverage run -m pytest -vvv tests/test_component/test_states.py
  - coverage run -m pytest -vvv tests/test_utils/test_*

after_success:
  - coverage combine
  - coverage xml
  - codecov
  - curl -s https://codecov.io/bash | bash

# rabbitmq
services:
- rabbitmq
- mongodb