language: python
python: "2.7"
  
# command to install dependencies
install: 
  - pip install .
  - pip install git+https://github.com/radical-cybertools/radical.utils.git@devel
  - pip install git+https://github.com/radical-cybertools/saga-python.git@devel
  - pip install git+https://github.com/radical-cybertools/radical.pilot.git@devel

#env variables
env:
  - RP_ENABLE_OLD_DEFINES=True RADICAL_PILOT_DBURL=mongodb://entk:entk@ds129010.mlab.com:29010/test_entk

# command to run tests
script: python -m pytest -v /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/radical/entk/tests

# rabbitmq
services:
  - rabbitmq