language: python
python: "2.7.13"
  
# command to install dependencies
install: 
  - pip install .
  - pip install pytest pytest-cov
  - pip install codecov

#env variables
env:
  - RP_ENABLE_OLD_DEFINES=True RADICAL_PILOT_DBURL=mongodb://entk:entk@ds129013.mlab.com:29013/travis_tests


script: python -m pytest -v /home/travis/build/radical-cybertools/radical.entk/tests --cov=./

# rabbitmq
services:
  - rabbitmq

after_success:
  - codecov