language: python
python: "2.7"

branches:
  - master
  - devel

os:
  - linux


env:
  global:
    - RADICAL_PILOT_DBURL="mongodb://entk:entk123@127.0.0.1:27017/entk_test"
    - RADICAL_PILOT_DBURL="mongodb://rct:rct_test@138.201.86.166/rct_test"
    - CODECOV_TOKEN="790b223f-07e4-4707-bb97-3abe58e29cd8"
    - LOG=`git log -n 1 | grep Merge`
    - OLD=`echo $LOG | cut -d ' ' -f2`
    - NEW=`echo $LOG | cut -d ' ' -f3`
    - DIFF=`git diff --name-only --diff-filter=b $OLD...$NEW`
    - DIFF=$(echo $DIFF | grep -o -e '\b[^ ]*.py\b')
    - PYTEST="coverage run -m pytest -ra --timeout=600 -vvv"
    - CMD_PYTEST="$PYTEST tests/test_component/*.py ;
                  $PYTEST tests/test_integration/test_*.py ;
                  $PYTEST tests/test_issues/test_* ;
                  $PYTEST tests/test_utils/test_*"
    - CMD_FLAKE8="if ! test -z \"$DIFF\"; then flake8 --config=.flake8 $DIFF;else echo 'Nothing to pep8'; fi"
    - CMD_PYLINT="if ! test -z \"$DIFF\"; then pylint $DIFF;else echo 'Nothing to lint';fi"
    - COVERAGE=false
  matrix:
    - MAIN_CMD=$CMD_PYTEST COVERAGE=true
    - MAIN_CMD=$CMD_FLAKE8
    - MAIN_CMD=$CMD_PYLINT


# command to install dependencies
install:
  - pip install .
  - pip install coverage
  - pip install flake8
  - pip install flake8-per-file-ignores
  - pip install pylint
  - pip install codecov
  - pip install pytest
  - pip install pytest-timeout

before_script:
# - sleep 5  # Ensures mongodb service is up
# - mongo entk_test --eval 'db.createUser({user:"entk",pwd:"entk123",roles:["readWrite"]});'
  - LOC=/home/travis/virtualenv/python2.7  # Location where VE is created on travis
  - sed -i 's|VENV|'"$LOC"'|g' .coveragerc  # Update source in coveragerc
  - cat .coveragerc

script:
  - echo $MAIN_CMD
  - eval $MAIN_CMD

after_success:
  - |
    if [[ $COVERAGE == 'true' ]]; then \
      coverage combine; \
      coverage xml; \
      coverage report; \
      curl -s https://codecov.io/bash | bash
    fi

services:
  - rabbitmq
# - mongodb

